imageRegistry: ""
dockerTag: "latest"
pullPolicy: "Always"
containerArgs: [ "npm", "run"]

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

service:
  enabled: false
  port: 5000
  uri: /default

env:
  HELLO: World
