---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- template "application.labels" | indent 2 }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      {{- template "application.labels" | indent 6 }}
  # {{- if .Values.serviceAccount }}
  # serviceAccountName: {{ .Values.serviceAccount.name }}
  # {{- end }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.imageRegistry }}:{{ .Values.dockerTag }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        {{- if .Values.containerArgs }}
        args: {{ .Values.containerArgs | toJson }}
        {{- end }}
        ports:
        - containerPort: 80
        env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | quote }}
            memory: {{ .Values.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.resources.limits.cpu | quote }}
            memory: {{ .Values.resources.limits.memory | quote }}