Transform: AWS::Serverless-2016-10-31
Description: Heroic Internal Developer Platform.

Globals:
  Function:
    Timeout: 300

Parameters:
  ENV:
    Type: String
    Description: Environment
    Default: dev

Resources:  

  HeroicApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Heroic-Api
      StageName: dev
      DefinitionBody:
        swagger: "2.0"
        info:
          title: Heroic API
          version: "1"
        paths:
          /v1/app:
            post:
              operationId: create-app
              description: "Invokes the heroic-create lambda function which creates a baseline pipeline, ECR repo and values.yml manifest."
              responses:
                "200":
                  description: "OK"
              x-amazon-apigateway-integration:
                payloadFormatVersion: "1.0"
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${HeroicAppCreateFunction}/invocations"

  HeroicAppCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app-create.lambda_handler
      Runtime: python3.8
      FunctionName: !Sub heroic-app-create-${ENV}
      Description: Creates a baseline pipeline, ECR repo and values.yml manifest.
      CodeUri: src/
      Events:
        HeroicApiEvent:
          Type: Api
          Properties:
            Path: /v1/app
            Method: post
            RestApiId: !Ref HeroicApiGateway
      Policies:
      - Statement:
        - Sid: S3GetObjectPolicy
          Effect: Allow
          Action:
          - s3:GetObject
          Resource: '*'
        - Sid: EcrRepositoryPolicy
          Effect: Allow
          Action:
          - ecr:DescribeRepositories
          - ecr:CreateRepository
          Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*