Transform: AWS::Serverless-2016-10-31
Description: Heroic Internal Developer Platform.

Globals:
  Function:
    Timeout: 300

Parameters:
  ENV:
    Type: String
    Description: Environment
    Default: dev

Resources:
  HeroicApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Heroic-Api
      StageName: ${ENV}
      DefinitionBody:
        swagger: "3.0"
        info:
          title: Heroic API
          version: "1"
        paths:
          /v1/app:
            post:
              operationId: create-app
              description: "Invokes the heroic-create lambda function which creates a baseline pipeline, ECR repo and values.yml manifest."
              responses:
                "200":
                  description: "OK"
              x-amazon-apigateway-integration:
                payloadFormatVersion: "1.0"
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${HeroicAppCreateFunction}/invocations"
                connectionType: "INTERNET"
                
  HeroicAppCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: heroic-create.handler
      Runtime: python3.8
      FunctionName: !Sub heroic-app-create-${ENV}
      Description: Creates a baseline pipeline, ECR repo and values.yml manifest.
      CodeUri: heroic-api/src/app-create.py
      Events:
        HeroicApiEvent:
          Type: Api
          Properties:
            Path: /v1/app
            Method: post
            RestApiId:
              Ref: HeroicApiGateway


    
    
  
  