name: heroic-api-chart-ci
on:
  push:
    paths:
      - "heroic-api/charts/**"
      - "heroic-api/scripts/chart_*"

  workflow_dispatch:
    home:
      required: false
      default: "Testing manual trigger"
      description: "location"

env:
  REGION: ap-southeast-2
  CHART_NAME: application

jobs:
  lint-and-template-chart:
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Template Application Chart
        run: heroic-api/scripts/chart_template.sh application

      - name: Test Application Chart
        run: heroic-api/scripts/chart_test.sh application

  package-and-release-chart:
    needs: lint-and-template-chart
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Package Application Chart
        run: heroic-api/scripts/chart_package.sh application
