name: heroic-api
on:
  push:
    paths:
      - '*'

env:
  REGION: ap-southeast-2
  APPLICATION_NAME: heroic-api

jobs:
  validate-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Terraform
        working-directory: heroic-api/infra/scripts
        run: terraform_validate.sh

  # lint-source:
  #   runs-on: ubuntu-latest
  #   working-directory: heroic-api
  #   steps:

  # test-source:
  #   runs-on: ubuntu-latest
  #   working-directory: heroic-api
  #   steps:

  # checkov-scan:
  #   runs-on: ubuntu-latest
  #   working-directory: heroic-api
  #   steps:

  # plan-infra:
  #   needs: validate-infra
  #   runs-on: ubuntu-latest 
  #   working-directory: heroic-api
  #   steps:

  # apply-infra:
  #   needs: plan-infra
  #   runs-on: ubuntu-latest
  #   working-directory: heroic-api
  #   steps:

  # build-and-upload-docker-image:
  #   needs: apply-infra





  
  